### ISSUE TITLE
port buzsaki conversion code

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/buzsaki-lab-to-nwb#1]
The Buzsaki lab uses Neuroscope format to store their raw data right now, the code to convert their data is here: https://github.com/ben-dichter-consulting/to_nwb/tree/master/to_nwb/Buzsaki, mostly in `convert_yuta.py`.  I'd like to move this over to this repo. We should use the Neuroscope Extractor where we can, but we will also need to port much of the custom code for behavior as well. We should also use the nwb conversion gui to allow the user to manually manage the meta-data

**Comment by CodyCBakerPhD** [comment]
I cannot guarantee the old nwb-gui works with the new format, but as far as I can tell all the stuff from the other repositories has been consolidated here. That said the web form (new gui) is coming along well apparently so shouldn't be too long until it's integrated well enough to work here.

**Comment by CodyCBakerPhD** [comment]
@bendichter Can this be closed?
