### ISSUE TITLE
convert to starting time and rate where appropriate

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/buzsaki-lab-to-nwb#3]
I have noticed that the position tracking has a constant sampling rate, yet we are treating it as irregularly sampled. This is making it more difficult to do analysis of this dataset.

**Comment by CodyCBakerPhD** [comment]
I'll give it another check, but I do believe we've resolved most of these.

**Comment by CodyCBakerPhD** [comment]
Yep, this has since been resolved in the new positional interfaces.
