### ISSUE TITLE
First ValeroM conversion

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/buzsaki-lab-to-nwb#54]
Past project, data collected and paper published.

Paper: [Probing subthreshold dynamics of hippocampal neurons by pulsed optogenetics](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9632609/)

Data: Buzsaki Globus, [ValeroM folder](https://app.globus.org/file-manager?origin_id=188a6110-96db-11eb-b7a9-f57b2d55370d&origin_path=%2FValeroM%2F)

<details>
<summary> Sessions
</summary>

```
datasets/ValeroM/fCamk1/fCamk1_200827_sess9
datasets/ValeroM/fCamk1/fCamk1_200901_sess12
datasets/ValeroM/unindexedSubjetcs/fCamk1/fCamk1_200902_sess13
datasets/ValeroM/unindexedSubjetcs/fCamk1/fCamk1_200904_sess15
datasets/ValeroM/unindexedSubjetcs/fCamk1/fCamk1_200908_sess16
datasets/ValeroM/unindexedSubjetcs/fCamk1/fCamk1_200909_sess17
datasets/ValeroM/unindexedSubjetcs/fCamk1/fCamk1_200910_sess18
datasets/ValeroM/unindexedSubjetcs/fCamk1/fCamk1_200911_sess19
datasets/ValeroM/unindexedSubjetcs/fCamk1/fCamk1_200911_sess19
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201028_sess10_cleanned
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201029_sess11_cleanned
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201030_sess12
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201103_sess14
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201111_sess20
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201113_sess22
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201105_sess16
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201106_sess17
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201110_sess19
datasets/ValeroM/unindexedSubjetcs/fCamk3/fCamk3_201109_sess18
datasets/ValeroM/unindexedSubjetcs/fCamk5/fCamk5_210406_sess10
datasets/ValeroM/unindexedSubjetcs/fCamk5/fCamk5_210407_sess11
datasets/ValeroM/unindexedSubjetcs/fCamk5/fCamk5_210408_sess12
datasets/ValeroM/unindexedSubjetcs/fCamk5/fCamk5_210414_sess16
datasets/ValeroM/unindexedSubjetcs/fCamk5/fCamk5_210412_sess14
datasets/ValeroM/unindexedSubjetcs/fCamk5/fCamk5_210415_sess17
datasets/ValeroM/unindexedSubjetcs/fCamk2/fCamk2_211012_sess1
datasets/ValeroM/unindexedSubjetcs/fCamk2/fCamk2_211013_sess2
datasets/ValeroM/unindexedSubjetcs/fCamk2/fCamk2_201014_sess3
datasets/ValeroM/unindexedSubjetcs/fCamk2/fCamk2_201015_sess4
```
</details>

Other info:

> The data from the published paper comes from 4 mice (CamKIIa)::Ai32 which were implanted with uLEDs probes (32ch with 12 light miniaturized LEDs) both in their home cages and in a linear maze. A unique aspect of the dataset is the pattern of light stimulation that we used (short and low intensity pulses in randomly assigend LEDs during ~3h per session). This is specified in two mat file named sessionName.pulses.events.mat. Let me know if you have any questions about this.

**Comment by CodyCBakerPhD** [comment]
Prototype: [/ValeroM/fCamk1/fCamk1_200827_sess9](https://app.globus.org/file-manager?origin_id=188a6110-96db-11eb-b7a9-f57b2d55370d&origin_path=%2FValeroM%2FfCamk1%2FfCamk1_200827_sess9%2F)

**Comment by h-mayorquin** [comment]
As for Valero, adding a preliminar to-do list here:

To-do for Valero conversion.
The skeleton of the conversion is onhttps://github.com/catalystneuro/buzsaki-lab-to-nwb/pull/61

- [ ]  Add Recording #61
- [ ] Add LFP #61 
- [ ] Modify either the interface or the sorter for CellExplorer to account for the new information. Right now, the sorting interface is added as an ad-hoc interface in #58. 
- [x] Add datetime for the session.
- [ ] Do an analysis of the mat files like the one for Huzsar
- [] Check behavior
- [ ] Check if specific time is available in any of the files.
- [ ] Add metadata for subject, experimenter, etc.
- [ ] Check for alignment between the different modalities.
- [ ] Run the conversion for all sessions.
- [ ] Create stub nwb files and share them with team for analysis.
- [ ] Once correct, run the conversion for all the files again and create a requirements.file with pin dependencies for this specific conversion.
- [ ] Upload conversion to dandi.
