### ISSUE TITLE
First HuszarR conversion

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/buzsaki-lab-to-nwb#55]
Past project, data collected and paper published.

Paper: [Preconfigured dynamics in the hippocampus are guided by embryonic birthdate and rate of neurogenesis](https://www.researchgate.net/publication/360752155_Preconfigured_dynamics_in_the_hippocampus_are_guided_by_embryonic_birthdate_and_rate_of_neurogenesis)

Data: Buzsaki Globus, [HuszarR folder,](https://app.globus.org/file-manager?origin_id=188a6110-96db-11eb-b7a9-f57b2d55370d&origin_path=%2FHuszarR%2F) everything under `optotagCA1`

Other info:

> The data was all recorded from mouse CA1- they are long recordings, many sessions have behavior on a familiar T-shaped maze, there are also animals that were exposed to both familiar and novel environments.
Some of the sessions were recorded with dual sided probes from Diagnostic Biochips, which gave us really good cell yield. One session has up to 480 cells, which is really great for ipsilateral CA1. 
Sessions with these high cells yields (we also have more that haven't been spike sorted) might be especially useful for the wider community.

> Another unique aspect of the dataset is that it includes information about the embryonic birthdate of pyramidal neurons, which (as it turns out) constrains the activity patterns across brain states (the paper is all about this).
The data is organized according to the embryonic birthdate of the cells, e.g, folder "e15" will have all animals where neurons of embryonic day 15 were targeted. There were 6 such animals (e.g., "e15_13f1"), and the folder of each holds the recording sessions that contributed to the analysis in the paper.
In the supplementary information of the paper (table 1, also attached), I describe what manipulations were done for each animal- it's not always the same.  

> In my case, all the data is in the folder HuszarR/optotagCA1, and it is primarily CellExplorer and buzcode-related formatting. 
I did not include any LFP data, although the ripple files include a single channel of LFP from the middle of the pyramidal layer. This works well for detection of events, but for finer timing-related LFP analysis (e.g., phase of hippocampal theta), this might be insufficient.
> Also I did not include any of the raw data in these folders.

I am talking to them about getting the raw data included in this conversion.

**Comment by CodyCBakerPhD** [comment]
Prototyping: /HuszarR/optotagCA1/e13/e13_16f1/e13_16f1_210302/

**Comment by h-mayorquin** [comment]
To-do for Huzsar conversion.
The skeleton of the conversion is on https://github.com/catalystneuro/buzsaki-lab-to-nwb/pull/58

- [ ] Cofirm that in the `SleepState.states` file, the timestamps match with the current event representation in #58
- [ ] Add position from `Behavior.mat` file
- [ ] Add trials from `Behavior` file.
- [ ] Modify either the interface or the sorter for CellExplorer to account for the new information. Right now, the sorting interface is added as an ad-hoc interface in #58. 
- [ ] Check if there is anything to add from the `ripples.events.mat`. Possible use https://pypi.org/project/ndx-events/ for this.
- [ ] Add datetime for the session.
- [ ] Wait to see how the recording data will look like. When that is available decide how to include the `chanMap.mat` information.
- [ ] Add metadata for subject, experimenter, etc.
- [ ] Run the conversion for all sessions.
- [ ] Create stub nwb files and share them with team for analysis.
- [ ] Once correct, run the conversion for all the files again and create a requirements.file with pin dependencies for this specific conversion.
- [ ] Upload conversion to dandi.

**Comment by CodyCBakerPhD** [comment]
Done and published

Great job both of you @h-mayorquin @garrettmflynn on this rapidly developed conversion, especially given how complex the data streams turned out to be
